---
#
# Installing Apache and necessary packages
#

- name: Install wget
  yum:
   name:
     - wget
   state: latest
  ignore_errors: yes 

- name: Install epl-repo
  shell: |
    wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    rpm -ivh epel-release-latest-7.noarch.rpm
  ignore_errors: yes
 
- name: Install pip
  yum:
    name:
       - python-pip
    state: latest
  ignore_errors: yes

- name: Install last version of pexpect
  command : "{{ item }}"
  with_items:
     - pip install pexpect
     - pip install --upgrade pip
  ignore_errors: yes

# Installing Apache 

- name: Install apache httpd
  yum:
   name: httpd
   state: present
   
# Security config of apache 

- name: Security config
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item.line }}'
  with_items:
     - line: 'ServerSignature Off'
     - line: 'ServerTokens Prod'

# Enable Apache
- name: enable apache to start up every time your server boots
  systemd:
    name: httpd
    enabled: yes
    masked: no

# Restart Apache
- name: Restarting apache
  systemd:
   name: httpd
   state: restarted
