---

- hosts: web
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
  - name: yum update
    command: yum update -y

  - name: Install awx
    yum:
     name:
         - epel-release
         - httpd
         - python-docker-py
         - git
         - gettext
         - ansible
         - docker
         - nodejs
         - npm
         - gcc-c++
         - bzip2
         - python-docker-py

  - name: clone de git
    shell: git clone https://github.com/ansible/awx.git

  - name: start docker
    command: systemctl start docker
    command: systemctl enable docker

  - name: install final
    command: cd /awx/installer/
    command: ansible-playbook -i inventory install.yml
 
...
