---
- hosts: Myservers 
  remote_user: root
  become: yes
  become_method: sudo 
  gather_facts: no
  tasks:
  - name : generate_key
    shell: 
     spawn ssh-keygen -t rsa
     expect "Enter file in which to save the key (/home/achref/.ssh/id_rsa):"
     send "\n"
     expect "Enter passphrase (empty for no passphrase):"
     send "\n"
     expect "Enter same passphrase again:"
     send "\n"
     interact
    args:
     executable: /usr/bin/expect

  - name: modify /etc/ssh/sshd_config
    replace:
     regexp: '^PasswordAuthentication no'
     replace: 'PasswordAuthentication yes'
     backup: yes

  - name : restart sshd
    service: 
     name: sshd
     state: restarted
 
  - name: share public key with clients
    shell: 
     spawn ssh-copy-id -i {{ansible_ssh_user}}@192.168.33.30
     expect "Are you sure you want to continue connecting (yes/no)?"
     send "yes\n"
     expect "@192.168.33.30's password:"
     send "{{ansible_ssh_password}}\n"
     exit 0
    args:
     executable: /usr/bin/expect


 
