---
- hosts: freeia_client3 
  remote_user: ansible_user
  become: yes
  become_method: sudo 
  gather_facts: yes
  tasks:
  - name : generate_key
    shell: 
     spawn ssh-keygen -t rsa
     expect "Enter file in which to save the key (/home/{{ansible_ssh_user}}/.ssh/id_rsa):"
     send "\n"
     expect "Enter passphrase (empty for no passphrase):"
     send "\n"
     expect "Enter same passphrase again:"
     send "\n"
     interact
    args:
     chdir: /home/{{ansible_ssh_user}}/.ssh
     executable: /usr/bin/expect

  - name: modify /etc/ssh/sshd_config
    replace:
     path: /etc/ssh/sshd_config
     regexp: '^PasswordAuthentication no'
     replace: 'PasswordAuthentication yes'
     backup: yes

  - name : restart sshd
    service: 
     name: sshd
     state: restarted
 
  - name: share public key with clients
    shell: 
     spawn ssh-copy-id -i {{ansible_ssh_user}}@192.168.33.17
     expect {Are you sure you want to continue connecting (yes/no)?}
     send "yes\n"
     expect "{{ansible_ssh_password}}@192.168.33.17's password:"
     send "{{ansible_ssh_password}}\n"
     interact
    args:
     chdir: /home/{{ansible_ssh_user}}/.ssh
     executable: /usr/bin/expect


 
