---

- hosts: Myservers
  remote_user: ansadm
  become: yes
  become_method: sudo
  tasks:
  - name: yum update
    command: yum update -y

  # Install necessary packages 
  - name: Install Curl and OpenJDK8 package
    yum:
     name:
       - curl
       - java-1.8.0-openjdk-devel
     state: latest
    ignore_errors: yes 
  
  #Install Jenkins
  - name: Enable Jenkins Repo
    shell: |
      curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | sudo tee /etc/yum.repos.d/jenkins.repo
      rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
    ignore_errors: yes
 
  - name: Install the latest stable version of Jenkins
    yum:
      name:
        - jenkins
      state: latest
    ignore_errors: yes

  # Enable Jenkins to start on boot 
  - name: Enable Jenkins service
    systemd:
      name: jenkins
      enabled: yes
      masked: no

  # Start Jenkins
  - name: Start Jenkins server
    systemd:
     name: jenkins
     state: started

  # Open Port 8080 if firewall is configured 
  - name: open port 8080
    shell: |
      firewall-cmd --permanent --zone=public --add-port=8080/tcp
      firewall-cmd --reload  
    ignore_errors: yes

  # Print the SuperAdmin Password
  #- name: Print SuperAdmin password to complete Installation 
  #  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  #  register: pass

  #- debug: AdmPass= "{{ pass.stdout }}"
