---
#
# Installing installing MySQL server
#

- name: Download and add the repository MYSQL
  command: "{{ item }} " 
  with_items:
      - pwd
      - wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
      - pwd 
      - rpm -ivh mysql-community-release-el7-5.noarch.rpm
  ignore_errors : yes 
   
- name: Installing MySQL
  yum: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql
    - MySQL-python
  ignore_errors : yes 

# Enable MySql at startup

- name: Enable MySQL at startup
  service: name=mysqld enabled=yes

# Start Mysql 

- name: start mysql
  systemd:
    name: "{{ item }}" 
    state: restarted
    daemon_reload: yes
  with_items:
       - 'mysqld'
  ignore_errors: yes 

#Config 

- name: Update MySQL root password
  mysql_user: name=root host={{ item }} password=root
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: True

- name: Delete anonymous MySQL user
  mysql_user: name="" state=absent login_user=root login_password=root

- name: Remove MySQL test database
  mysql_db: name=test state=absent login_user=root login_password=root
